title: "Michaels .NET Blog"
name: "Michael Schneider"
description: >
  Praxisnahe .NET-Entwicklung – fundiert, verständlich, direkt aus dem Maschinenraum.
  In diesem Blog teile ich Erkenntnisse aus über 20 Jahren Arbeit mit .NET – von der .NET-1.0-Beta bis hin zu modernen Cross-Plattform-Projekten.

url: "https://blog.schneider-michael.de"
baseurl: ""

remote_theme: "pages-themes/modernist@v0.2.0"
show_downloads: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

# Navigation
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: michael
      read_time: true
      comments: false
      share: true
      related: true

paginate: 5
paginate_path: /seite/:num/

author:
  michael:
    name: "Michael Schneider"
    bio: "Softwareentwickler mit 20+ Jahren .NET-Erfahrung"
    links:
      - label: "LinkedIn"
        icon: "fab fa-linkedin"
        url: "https://www.linkedin.com/in/michael-schneider-3a027233"
      - label: "Xing"
        icon: "fab fa-xing"
        url: "https://www.xing.com/profile/Michael_Schneider104"

# Footer
footer:
  links:
    - label: "Impressum"
      url: "https://schneider-michael.de/home/Impressum"

markdown: kramdown